[package]
name = "keel-preview"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true

[lib]
path = "src/lib.rs"

[features]
test-hooks = []

[dependencies]
syntect.workspace = true
pulldown-cmark.workspace = true
image.workspace = true
resvg.workspace = true
calamine.workspace = true
csv.workspace = true
pdfium-render.workspace = true
docx-rs.workspace = true
keel-vfs = { path = "../keel-vfs", default-features = false }
two-face = { version = "0.4", default-features = false, features = ["syntect-fancy"] }
wait-timeout = "0.2"

[dev-dependencies]
tempfile = "3"
