//! Keel's API (spec 2.10, "API and automation"): one compile-time list of typed operations,
//! [`OPS`], serves JSON-RPC (`keel-daemon`), the `keel` CLI subcommands and the MCP server
//! (`keel mcp`). Each [`Operation`] has a name, a summary, JSON schemas for its parameters
//! and result (generated by `schemars` from the Rust types in [`types`]) and a handler.
//!
//! Mutating operations are preview-first: called directly, they only validate their input
//! and return a [`types::PlanPreview`] (a plan id plus the hash of the exact input);
//! `execute` with that id and hash applies it, refusing tampered or expired plans. File
//! operations go through `plan` (keel-core's `validate -> preview -> execute`). Only
//! `shares.revoke` (taking access away) and `recents.note` (an opened file) act directly.
//! Mounts (`mounts.*`) need a host that serves them ([`Ctx::mounts`], set by keel-daemon).

pub mod client;
pub mod config;
pub mod daemon_provider;
pub mod error;
pub mod files;
pub mod host;
pub mod mcp;
pub mod net;
mod ops;
pub mod plans;
pub mod private;
pub mod rpc;
pub mod socket;
pub mod types;

pub use daemon_provider::DaemonProvider;
pub use error::{ApiError, Result};
pub use ops::OPS;
pub use plans::PlanStore;

use serde::{de::DeserializeOwned, Serialize};
use serde_json::Value;
use std::sync::Arc;

/// API revision reported by `version`.
pub const API_VERSION: u32 = 1;

/// What every handler gets: the open library, the VFS router, keel-net when enabled, the
/// mounts when this host serves them, and the plans waiting for `execute`.
pub struct Ctx {
    pub lib: Arc<keel_core::Library>,
    pub router: Arc<keel_vfs::Router>,
    pub node: Option<Arc<keel_net::Node>>,
    /// Runs the node's async calls (set with `node`).
    pub rt: Option<tokio::runtime::Handle>,
    /// Sources mounted as drives; only a long-lived host (keel-daemon) serves them.
    pub mounts: Option<Arc<keel_mount::Mounts>>,
    pub plans: PlanStore,
    /// Seconds east of UTC, for `dm:` dates in search queries.
    pub utc_offset: i64,
    /// One-time links made by `file.get`.
    pub downloads: files::Downloads,
    /// Keel's configuration folder (the daemon token, keys): never readable through the
    /// read operations.
    pub config_dir: Option<std::path::PathBuf>,
    /// The Spacedrop inbox and waiting offers (set with `node` by a host).
    pub drops: Option<Arc<net::Drops>>,
    /// Keel's data folder (the library database, device keys, share uploads, the mount
    /// spool): never sent with `spacedrop.send`, except the inbox and opened shares.
    pub data_dir: Option<std::path::PathBuf>,
}

/// `<data dir>/shares/<id>/` holds a Web Share Target upload; this file in it marks one the
/// signed-in client opened (keel-daemon writes it on `share.claim`), which
/// `spacedrop.send` may then send.
pub const SHARE_CLAIMED: &str = ".claimed";

impl Ctx {
    /// Plans are kept in `<library dir>/api-plans.json`.
    pub fn new(lib: Arc<keel_core::Library>, router: Arc<keel_vfs::Router>) -> Self {
        let plans = PlanStore::open(lib.dir().join("api-plans.json"), plans::TTL);
        Self {
            lib,
            router,
            node: None,
            rt: None,
            mounts: None,
            plans,
            utc_offset: 0,
            downloads: Default::default(),
            config_dir: config::config_dir(),
            drops: None,
            data_dir: None,
        }
    }

    pub fn with_net(mut self, node: Arc<keel_net::Node>, rt: tokio::runtime::Handle) -> Self {
        self.node = Some(node);
        self.rt = Some(rt);
        self
    }

    pub fn with_mounts(mut self, mounts: Arc<keel_mount::Mounts>) -> Self {
        self.mounts = Some(mounts);
        self
    }

    pub fn with_plans(mut self, plans: PlanStore) -> Self {
        self.plans = plans;
        self
    }
}

pub type Handler = fn(&Ctx, Value) -> Result<Value>;

/// How an operation runs.
pub enum Run {
    /// At once: reads, `plan`, `execute`, and `shares.revoke`.
    Now(Handler),
    /// Called directly it only previews (stored as a plan); `execute` runs `apply`.
    Previewed {
        preview: fn(&Ctx, &Value) -> Result<Preview>,
        apply: Handler,
        /// Schema of what `apply` returns (inside `Executed::result`).
        applied: fn() -> Value,
        /// Parameters hold a secret (a pairing code): the plan never touches disk.
        secret: bool,
    },
}

/// What a previewed operation would do, before it gets its plan id.
pub struct Preview {
    pub summary: String,
    pub changes: Vec<types::Change>,
    pub warnings: Vec<types::Warning>,
    /// Stored in the plan's params as `pinned` (what the preview showed, e.g. the hash of
    /// the files a drop sends): `apply` compares it and refuses with PLAN_CHANGED.
    pub pin: Option<Value>,
}

pub struct Operation {
    /// Stable id: `sources.add`, `tags.list`, … (MCP tools use `_` for `.`).
    pub name: &'static str,
    pub summary: &'static str,
    /// Changes the library, files, devices or grants.
    pub mutating: bool,
    /// JSON schema of the parameters (an object).
    pub params: fn() -> Value,
    /// JSON schema of the result of a direct call (a `PlanPreview` for previewed ones).
    pub result: fn() -> Value,
    /// Example parameters (they validate against `params`).
    pub example: fn() -> Value,
    /// Deserializes parameters into the operation's type and back (canonical form).
    pub check: fn(Value) -> Result<Value>,
    pub run: Run,
}

impl Operation {
    pub fn previewed(&self) -> bool {
        matches!(self.run, Run::Previewed { .. })
    }
}

pub fn find(name: &str) -> Option<&'static Operation> {
    OPS.iter().find(|op| op.name == name)
}

/// Runs `method` against `ctx`: a read returns its result, a previewed operation its
/// preview (stored for `execute`). Missing or null params are `{}`.
pub fn call(ctx: &Ctx, method: &str, params: Value) -> Result<Value> {
    let op = find(method).ok_or_else(|| {
        ApiError::new(ApiError::METHOD_NOT_FOUND, format!("no operation {method}"))
    })?;
    let params = match params {
        Value::Null => Value::Object(Default::default()),
        Value::Object(_) => params,
        _ => return Err(ApiError::invalid_params("params must be an object")),
    };
    match op.run {
        Run::Now(handler) => handler(ctx, params),
        Run::Previewed {
            preview, secret, ..
        } => {
            let mut params = (op.check)(params)?;
            let p = preview(ctx, &params)?;
            if let (Some(pin), Some(obj)) = (p.pin, params.as_object_mut()) {
                obj.insert("pinned".into(), pin);
            }
            let input = plans::Input::Call {
                method: op.name.to_owned(),
                params,
            };
            let (plan_id, input_hash, expires_at) = ctx.plans.insert(input, secret)?;
            to_value(types::PlanPreview {
                plan_id,
                input_hash,
                operation: op.name.to_owned(),
                summary: p.summary,
                changes: p.changes,
                warnings: p.warnings,
                expires_at,
            })
        }
    }
}

/// Somewhere to send calls: a [`Ctx`] in this process or a daemon over its socket.
pub trait Backend {
    fn call(&mut self, method: &str, params: Value) -> Result<Value>;
}

impl Backend for Ctx {
    fn call(&mut self, method: &str, params: Value) -> Result<Value> {
        call(self, method, params)
    }
}

/// The JSON schema of `T` with every subschema inlined (MCP clients want plain objects).
pub fn schema<T: schemars::JsonSchema>() -> Value {
    let generator = schemars::generate::SchemaSettings::draft2020_12()
        .with(|s| s.inline_subschemas = true)
        .into_generator();
    generator.into_root_schema_for::<T>().to_value()
}

pub(crate) fn parse<T: DeserializeOwned>(v: Value) -> Result<T> {
    serde_json::from_value(v).map_err(|e| ApiError::invalid_params(e.to_string()))
}

pub(crate) fn to_value<T: Serialize>(v: T) -> Result<Value> {
    serde_json::to_value(v).map_err(|e| ApiError::new(ApiError::INTERNAL, e.to_string()))
}

pub(crate) fn check<T: DeserializeOwned + Serialize>(v: Value) -> Result<Value> {
    to_value(parse::<T>(v)?)
}

#[cfg(test)]
mod tests;
