[package]
name = "keel-vfs"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true

[lib]
path = "src/lib.rs"

[dependencies]
anyhow.workspace = true
thiserror.workspace = true
serde.workspace = true
parking_lot.workspace = true
crossbeam-channel.workspace = true
russh.workspace = true
russh-sftp.workspace = true
tokio.workspace = true
keyring.workspace = true
ssh-key.workspace = true
dirs.workspace = true
sha2.workspace = true
hmac.workspace = true
sha1.workspace = true
tempfile = "3"
notify = "6"
notify-debouncer-mini = "0.4"
natord = "1"
rayon = "1"
walkdir = "2"
same-file = "1"
trash = "5"
sysinfo = { version = "0.32", default-features = false, features = ["disk"] }

[target.'cfg(windows)'.dependencies]
windows.workspace = true

[dev-dependencies]
toml.workspace = true
