[package]
name = "keel-search"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true

[lib]
path = "src/lib.rs"

[dependencies]
anyhow.workspace = true
keel-vfs = { path = "../keel-vfs" }
libloading.workspace = true
nucleo.workspace = true
parking_lot.workspace = true
windows.workspace = true
